# correlationsearches.conf
[Suspicious_Logon]
annotations = risk_score=80
description = Admin logon from non-whitelisted IP
enabled = 1
severity = high

[Multiple_Failed_Logins]
annotations = risk_score=30m
description = medium
enabled = 1
severity = medium

[Outbound_to_Rare_Country]
annotations = risk_score=0
description = low
enabled = 1
severity = medium

[Regex_Match_Example]
annotations = risk_score=40
description = Access to suspicious paths
enabled = 1
severity = critical

[QR_Suspicious_Logon_XML]
annotations = risk_score=0
description = XML exported rule
enabled = 1
severity = high

