# savedsearches.conf
[Suspicious_Logon]
search = search index=main earliest=-15m latest=now | where user='admin' AND src!='10.0.0.1'
cron_schedule = */5 * * * *
enabled = 1
dispatch.earliest_time = 0
dispatch.latest_time = now
description = Admin logon from non-whitelisted IP
action.notable = 1
action.notable.severity = high
action.notable.rule_name = $name$
action.notable.category = Correlation
action.notable.drilldown_name = View Search Results
action.notable.drilldown_search = $search$
alert.suppress = 1
alert.suppress.fields = user
alert.suppress.period = 15m

[Multiple_Failed_Logins]
search = search index=main
cron_schedule = * * * * *
enabled = 1
dispatch.earliest_time = 0
dispatch.latest_time = now
description = medium
action.notable = 1
action.notable.severity = medium
action.notable.rule_name = $name$
action.notable.category = Correlation
action.notable.drilldown_name = View Search Results
action.notable.drilldown_search = $search$
alert.suppress = 1
alert.suppress.fields = 50
alert.suppress.period = 15m

[Outbound_to_Rare_Country]
search = search index=main | where destinationip IN ('203.0.113.10'
cron_schedule = * * * * *
enabled = 1
dispatch.earliest_time = 0
dispatch.latest_time = now
description = low
action.notable = 1
action.notable.severity = medium
action.notable.rule_name = $name$
action.notable.category = Correlation
action.notable.drilldown_name = View Search Results
action.notable.drilldown_search = $search$
alert.suppress = 1
alert.suppress.fields = 20
alert.suppress.period = 15m

[Regex_Match_Example]
search = search index=main earliest=-5m latest=now | where match(url, ".*(/wp-admin|/xmlrpc)\b.*")
cron_schedule = */5 * * * *
enabled = 1
dispatch.earliest_time = 0
dispatch.latest_time = now
description = Access to suspicious paths
action.notable = 1
action.notable.severity = critical
action.notable.rule_name = $name$
action.notable.category = Correlation
action.notable.drilldown_name = View Search Results
action.notable.drilldown_search = $search$
alert.suppress = 1
alert.suppress.fields = src
alert.suppress.period = 15m

[QR_Suspicious_Logon_XML]
search = search index=main earliest=-15m latest=now | where user='root' AND NOT ((src="10.*" OR src="192.168.*" OR src="172.16.*"))
cron_schedule = */5 * * * *
enabled = 1
dispatch.earliest_time = 0
dispatch.latest_time = now
description = XML exported rule
action.notable = 1
action.notable.severity = high
action.notable.rule_name = $name$
action.notable.category = Correlation
action.notable.drilldown_name = View Search Results
action.notable.drilldown_search = $search$

